# Generated by Django 4.2.2 on 2023-06-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emsidoc_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Attestation', 'Attestation'), ('Aval', 'Aval'), ('certificat de preuve d identite', 'certificat de preuve d identite'), ('certificat d enagement', 'certificat d enagement')], max_length=255)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_enregistrement', models.DateField()),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsidoc_admin.user')),
            ],
        ),
    ]
