# Generated by Django 4.2.2 on 2023-07-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsidoc_sharedmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Signed', 'Signed'), ('Not Signed', 'Not Signed')], default='Not Signed', max_length=255),
        ),
    ]
