# Generated by Django 4.2.2 on 2023-07-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsidoc_sharedmodel', '0002_document_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='id',
            new_name='Doc_id',
        ),
    ]
