# Generated by Django 4.2.2 on 2023-07-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsidoc_sharedmodel', '0003_rename_id_document_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Signed', 'Signed'), ('Not Signed', 'Not Signed')], default='En cours', max_length=255),
        ),
    ]
