# Generated by Django 4.2.2 on 2023-07-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsidoc_sharedmodel', '0004_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Signed', 'Signed'), ('Rejected', 'Rejected')], default='En cours', max_length=255),
        ),
    ]
