# Generated by Django 4.2.2 on 2023-07-11 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emsidoc_admin', '0004_alter_user_signature'),
        ('emsidoc_sharedmodel', '0006_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_enregistrement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emsidoc_admin.user'),
        ),
    ]
