# Generated by Django 4.2.2 on 2023-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=255)),
                ('Prenom', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('signature', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=255)),
            ],
        ),
    ]
