# Generated by Django 4.2.2 on 2023-06-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsidoc_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Fonctionnaire', 'Fonctionnaire'), ('citoyen', 'citoyen')], max_length=255),
        ),
    ]
