# Generated by Django 4.2.2 on 2023-07-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsidoc_admin', '0003_alter_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.FileField(upload_to='signatures/'),
        ),
    ]
